
const words = {
  easy: [
    { word: 'airplane', definition: 'a powered flying vehicle with fixed wings and a weight greater than that of the air it displaces' },
    { word: 'apple', definition: 'the round fruit of a tree of the rose family, which typically has thin red or green skin and crisp flesh' },
    { word: 'banana', definition: 'a long curved fruit that grows in clusters and has soft pulpy flesh and yellow skin when ripe' },
    { word: 'boat', definition: 'a small vessel propelled on water by oars, sails, or an engine' },
    { word: 'bus', definition: 'a large motor vehicle carrying passengers by road, especially one serving the public on a fixed route and for a fare' },
    { word: 'car', definition: 'a road vehicle, typically with four wheels, powered by an internal combustion engine and able to carry a small number of people' },
    { word: 'grape', definition: 'the edible, pulpy, smooth-skinned berry or fruit that grows in clusters on vines of the genus Vitis' },
    { word: 'lemon', definition: 'a yellow, oval citrus fruit with thick skin and fragrant, acidic juice' },
    { word: 'lime', definition: 'a green, oval fruit whose juice has a sour taste' },
    { word: 'orange', definition: 'a round juicy citrus fruit with a tough bright reddish-yellow rind' },
    { word: 'peach', definition: 'a round stone fruit with juicy yellow flesh and downy pinkish-yellow skin' },
    { word: 'pear', definition: 'a yellowish- or brownish-green edible fruit that is typically narrow at the stalk and wider toward the base, with sweet, slightly gritty flesh' },
    { word: 'truck', definition: 'a large, heavy motor vehicle used for transporting goods, materials, or troops' },
    { word: 'train', definition: 'a series of railroad cars moved as a unit by a locomotive or by integral motors' },
    { word: 'taxi', definition: 'an automobile that carries passengers for a fare usually determined by the distance traveled' },
  ],
  medium: [
    { word: 'abbreviate', definition: 'shorten (a word, phrase, or text)' },
    { word: 'absorbent', definition: 'able to soak up liquid easily' },
    { word: 'accommodate', definition: 'provide lodging or sufficient space for' },
    { word: 'acquiesce', definition: 'accept something reluctantly but without protest' },
    { word: 'aegis', definition: 'the protection, backing, or support of a particular person or organization' },
    { word: 'aesthetic', definition: 'concerned with beauty or the appreciation of beauty' },
    { word: 'aggravate', definition: 'make (a problem, injury, or offense) worse or more serious' },
    { word: 'archaeology', definition: 'the study of human history and prehistory through the excavation of sites and the analysis of artifacts and other physical remains' },
    { word: 'broccoli', definition: 'a cabbage of a variety similar to the cauliflower, bearing heads of green or purplish flower buds. It is widely cultivated as a vegetable' },
    { word: 'Caribbean', definition: 'the sea which is between the West Indies, Central America, and the north coast of South America' },
    { word: 'casserole', definition: 'a kind of stew or side dish that is cooked slowly in an oven' },
    { word: 'cemetery', definition: 'a burial ground; a graveyard' },
    { word: 'chandelier', definition: 'a decorative hanging light with branches for several light bulbs or candles' },
    { word: 'cognizant', definition: 'having knowledge or being aware of' },
    { word: 'commission', definition: 'an instruction, command, or duty given to a person or group of people' },
    { word: 'Connecticut', definition: 'a New England state; one of the original 13 colonies' },
    { word: 'connoisseur', definition: 'an expert judge in matters of taste' },
    { word: 'conscience', definition: 'an inner feeling or voice viewed as acting as a guide to the rightness or wrongness of one\'s behavior' },
    { word: 'curriculum', definition: 'the subjects comprising a course of study in a school or college' },
    { word: 'deductible', definition: 'able to be deducted, especially from taxable income or tax to be paid' },
    { word: 'deplorable', definition: 'deserving strong condemnation' },
    { word: 'dilemma', definition: 'a situation in which a difficult choice has to be made between two or more alternatives, especially equally undesirable ones' },
    { word: 'doorjamb', definition: 'each of the two upright parts of a doorframe, on one of which the door is hung' },
    { word: 'embarrass', definition: 'cause (someone) to feel awkward, self-conscious, or ashamed' },
    { word: 'epitome', definition: 'a person or thing that is a perfect example of a particular quality or type' },
    { word: 'fuchsia', definition: 'a shrub with pendulous tubular flowers that are typically of two contrasting colors. They are native to America and New Zealand and are commonly grown as ornamentals' },
    { word: 'genealogy', definition: 'a line of descent traced continuously from an ancestor' },
    { word: 'geyser', definition: 'a hot spring in which water intermittently boils, sending a tall column of water and steam into the air' },
    { word: 'harass', definition: 'subject to aggressive pressure or intimidation' },
    { word: 'hemorrhage', definition: 'an escape of blood from a ruptured blood vessel, especially when profuse' },
    { word: 'hydraulics', definition: 'the branch of science and technology concerned with the conveyance of liquids through pipes and channels, especially as a source of mechanical force or control' },
    { word: 'inferable', definition: 'to derive by reasoning' },
    { word: 'inoculate', definition: 'treat (a person or animal) with a vaccine to produce immunity against a disease' },
    { word: 'maintenance', definition: 'the process of maintaining or preserving someone or something, or the state of being maintained' },
    { word: 'millennium', definition: 'a period of a thousand years, especially when calculated from the traditional date of the birth of Christ' },
    { word: 'occurred', definition: 'something that happened, took place, existed or was found' },
    { word: 'playwright', definition: 'a person who writes plays' },
    { word: 'recommend', definition: 'put forward (someone or something) with approval as being suitable for a particular purpose or role' },
    { word: 'supersede', definition: 'take the place of (a person or thing previously in authority or use); supplant' },
    { word: 'pheasant', definition: 'a large long-tailed game bird native to Asia, the male of which typically has very showy plumage' },
    { word: 'illegitimate', definition: 'not authorized by the law; not in accordance with accepted standards or rules' },
    { word: 'inflammation', definition: 'a localized physical condition in which part of the body becomes reddened, swollen, hot, and often painful, especially as a reaction to injury or infection' },
    { word: 'interrupt', definition: 'stop the continuous progress of (an activity or process)' },
    { word: 'jeopardize', definition: 'put (someone or something) into a situation in which there is a danger of loss, harm, or failure' },
    { word: 'kaleidoscope', definition: 'a toy consisting of a tube containing mirrors and pieces of colored glass or paper, whose reflections produce changing patterns that are visible through an eyehole when the tube is rotated' },
    { word: 'knowledgeable', definition: 'intelligent and well informed' },
    { word: 'labyrinth', definition: 'a complicated irregular network of passages or paths in which it is difficult to find one\'s way; a maze' },
    { word: 'lachrymose', definition: 'tearful or given to weeping' },
    { word: 'lenient', definition: '(of punishment or a person in authority) permissive, merciful, or tolerant' },
    { word: 'maelstrom', definition: 'a powerful whirlpool in the sea or a river' },
    { word: 'mannequin', definition: 'a dummy used to display clothes in a store window' },
    { word: 'marquee', definition: 'a rooflike projection over the entrance to a theater, hotel, or other building' },
    { word: 'matinee', definition: 'a performance in a theater or a showing of a movie that takes place in the daytime' },
    { word: 'medieval', definition: 'relating to the Middle Ages' },
    { word: 'mnemonic', definition: 'a device such as a pattern of letters, ideas, or associations that assists in remembering something' },
    { word: 'paraphernalia', definition: 'miscellaneous articles, especially the equipment needed for a particular activity' },
    { word: 'parfait', definition: 'a dessert consisting of layers of ice cream, fruit, etc., served in a tall glass' },
  ],
  hard: [
    { word: 'arcology', definition: 'a field of creating architectural design principles for very densely populated, ecologically low-impact human habitats' },
    { word: 'assuage', definition: 'make (an unpleasant feeling) less intense' },
    { word: 'bourgeoisie', definition: 'the middle class, typically with reference to its perceived materialistic values or conventional attitudes' },
    { word: 'carafe', definition: 'an open-topped glass flask typically used for serving wine or water' },
    { word: 'ceraceous', definition: 'waxlike or waxy' },
    { word: 'connoisseur', definition: 'an expert judge in matters of taste' },
    { word: 'dirigible', definition: 'capable of being steered, guided, or directed' },
    { word: 'dossier', definition: 'a collection of documents about a particular person, event, or subject' },
    { word: 'execrable', definition: 'extremely bad or unpleasant' },
    { word: 'fallibility', definition: 'the tendency to make mistakes or be wrong' },
    { word: 'gerontology', definition: 'the scientific study of old age, the process of aging, and the particular problems of old people' },
    { word: 'gnathonic', definition: 'deceitfully flattering' },
    { word: 'hafiz', definition: 'a Muslim who knows the Koran by heart' },
    { word: 'hauteur', definition: 'haughtiness of manner; disdainful pride' },
    { word: 'hoyle', definition: 'according to plan or the rules' },
    { word: 'ingenue', definition: 'an innocent or unsophisticated young woman, especially in a play or film' },
    { word: 'insalubrious', definition: 'not conducive to health' },
    { word: 'jodhpurs', definition: 'full-length trousers, worn for horseback riding, that are close-fitting below the knee and have reinforced patches on the inside of the leg' },
    { word: 'lacertilian', definition: 'a lizard' },
    { word: 'lecithin', definition: 'a substance widely distributed in animal tissues, egg yolk, and some higher plants, consisting of phospholipids linked to choline' },
    { word: 'lugubrious', definition: 'looking or sounding sad and dismal' },
    { word: 'metastasize', definition: '(of malignant cells or disease-producing organisms) to spread to other parts of the body by way of the blood or lymphatic vessels or membranous surfaces.' },
    { word: 'minyan', definition: 'a quorum of ten men (or in some synagogues, men and women) over the age of 13 required for traditional Jewish public worship' },
    { word: 'myrrh', definition: 'a fragrant gum resin obtained from certain trees and used, especially in the Near East, in perfumery, medicines, and incense' },
    { word: 'nepenthe', definition: 'a drug or drink, or the plant yielding it, mentioned by ancient writers as having the power to bring forgetfulness of sorrow or trouble' },
    { word: 'nisei', definition: 'a person born in the US or Canada whose parents were immigrants from Japan' },
    { word: 'onomatopoeia', definition: 'the formation of a word from a sound associated with what is named' },
    { word: 'oppugn', definition: 'call into question the truth or validity of' },
    { word: 'ordnance', definition: 'mounted guns; artillery' },
    { word: 'palilalia', definition: 'a speech disorder characterized by involuntary repetition of words, phrases, or sentences' },
    { word: 'panettone', definition: 'a rich Italian bread made with eggs, fruit, and butter and typically eaten at Christmas' },
    { word: 'sassafras', definition: 'a deciduous North American tree with aromatic leaves and bark' },
  ]
};

export default words;
